version: '3.8'
services: 
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-3.2.1-java8
    container_name: namenode 
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    networks:
      - netw

  datanode-1:
    image: bde2020/hadoop-datanode:2.0.0-3.2.1-java8
    container_name: datanode-1
    restart: always
    ports:
      - 9864:9864
    volumes: 
      - hadoop_datanode_1:/hadoop/dfs/data
    enironment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      - netw



  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    networks:
      - netw
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker-1:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-1
    networks:
      - netw
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"


  

networks:
  netw:
    driver: "bridge"



